name: Install LLVM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'LLVM version to install'
        required: true
        default: '15'

jobs:
  install-llvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Purge clang and LLVM
      run: |
        sudo apt purge clang* llvm*
    - name: Install LLVM
      run: |
        bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" ${{ github.event.inputs.version }}

    - name: Check LLVM version
      run: |
        clang --version