name: Install LLVM

on:
  push:
    branches:
      - main

jobs:
  install-llvm:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install LLVM
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"

    - name: Check LLVM version
      run: |
        clang --version
